const AG_GRID_LOCALE_HE = {
    // Set Filter
    selectAll: '(בחר הכל)',
    selectAllSearchResults: '(בחר את כל תוצאות החיפוש)',
    searchOoo: 'חיפוש...',
    blanks: '(ריק)',
    noMatches: 'אין התאמות',

    // Number Filter & Text Filter
    filterOoo: 'סינון...',
    equals: 'שווה',
    notEqual: 'לא שווה',
    blank: 'ריק',
    notBlank: 'לא ריק',
    empty: 'בחר',

    // Number Filter
    lessThan: 'פחות מ',
    greaterThan: 'גדול מ',
    lessThanOrEqual: 'פחות או שווה ל',
    greaterThanOrEqual: 'גדול או שווה ל',
    inRange: 'בטווח',
    inRangeStart: 'מ',
    inRangeEnd: 'עד',

    // Text Filter
    contains: 'מכיל',
    notContains: 'לא מכיל',
    startsWith: 'מתחיל עם',
    endsWith: 'מסתיים עם',

    // Date Filter
    dateFormatOoo: 'yyyy-mm-dd',

    // Filter Conditions
    andCondition: 'וגם',
    orCondition: 'או',

    // Filter Buttons
    applyFilter: 'החל',
    resetFilter: 'אפס',
    clearFilter: 'נקה',
    cancelFilter: 'ביטול',

    // Filter Titles
    textFilter: 'סינון טקסט',
    numberFilter: 'סינון מספרים',
    dateFilter: 'סינון תאריכים',
    setFilter: 'הגדר סינון',

    // Group Column Filter
    groupFilterSelect: 'בחר שדה:',

    // Side Bar
    columns: 'עמודות',
    filters: 'מסננים',

    // columns tool panel
    pivotMode: 'מצב צירופים',
    groups: 'קבוצות שורות',
    rowGroupColumnsEmptyMessage: 'גרור לכאן כדי להגדיר קבוצות שורות',
    values: 'ערכים',
    valueColumnsEmptyMessage: 'גרור לכאן כדי לסכם',
    pivots: 'תגיות עמודות',
    pivotColumnsEmptyMessage: 'גרור לכאן כדי להגדיר תגיות עמודות',

    // Header of the Default Group Column
    group: 'קבוצה',

    // Row Drag
    rowDragRow: 'שורה',
    rowDragRows:'שורות',

    // Other
    loadingOoo: 'טוען...',
    loadingError: 'שגיאה',
    noRowsToShow: 'אין שורות להצגה',
    enabled: 'מאופשר',

    // Menu
    pinColumn: 'נעיצת עמודה',
    pinLeft: 'נעיצה לשמאל',
    pinRight: 'נעיצה לימין',
    noPin: 'לא לנעיצה',
    valueAggregation: 'סיכום ערכים',
    noAggregation: 'אין',
    autosizeThiscolumn: 'התאם רוחב עמודה זו',
    autosizeAllColumns: 'התאם רוחב לכל העמודות',
    groupBy: 'קיבוץ לפי',
    ungroupBy: 'הפסק קיבוץ לפי',
    addToValues: 'הוסף ${variable} לערכים',
    removeFromValues: 'הסר ${variable} מהערכים',
    addToLabels: 'הוסף ${variable} לתוויות',
    removeFromLabels: 'הסר ${variable} מהתוויות',
    resetColumns: 'איפוס עמודות',
    expandAll: 'הרחבת כל קבוצות השורות',
    collapseAll: 'כיווץ כל קבוצות השורות',
    copy: 'העתק',
    ctrlC: 'Ctrl+C',
    ctrlX: 'Ctrl+X',
    copyWithHeaders: 'העתק עם כותרות',
    copyWithGroupHeaders: 'העתק עם כותרות קבוצה',
    cut: 'גזור',
    paste: 'הדבק',
    ctrlV: 'Ctrl+V',
    export: 'יצוא',
    csvExport: 'יצוא ל-CSV',
    excelExport: 'יצוא ל-Excel',

    // Enterprise Menu Aggregation and Status Bar
    sum: 'סכום',
    first: 'ראשון',
    last: 'אחרון',
    min: 'מינימום',
    max: 'מקסימום',
    none: 'ללא',
    count: 'ספירה',
    avg: 'ממוצע',
    filteredRows: 'סוננו',
    selectedRows: 'נבחרו',
    totalRows: 'סך הכל שורות',
    totalAndFilteredRows: 'שורות',
    more: 'עוד',
    to: 'עד',
    of: 'מתוך',
    page: 'עמוד',
    pageLastRowUnknown: '?',
    nextPage: 'עמוד הבא',
    lastPage: 'עמוד אחרון',
    firstPage: 'עמוד ראשון',
    previousPage: 'עמוד קודם',

    // Pivoting
    pivotColumnGroupTotals: 'סכומים',

    // Enterprise Menu (Charts)
    pivotChartAndPivotMode: 'תרשים צירופים ומצב צירופים',
    pivotChart: 'תרשים צירופים',
    chartRange: 'טווח תרשים',

    columnChart: 'עמודות',
    groupedColumn: 'קיבוץ',
    stackedColumn: 'מוערכות',
    normalizedColumn: 'מוערכות 100%',

    barChart: 'טורים',
    groupedBar: 'קיבוץ',
    stackedBar: 'מוערכות',
    normalizedBar: 'מוערכות 100%',

    pieChart: 'עוגה',
    pie: 'עוגה',
    doughnut: 'תופסת',

    line: 'קו',

    xyChart: 'XY (פיזור)',
    scatter: 'פיזור',
    bubble: 'בועה',

    areaChart: 'אזור',
    area: 'אזור',
    stackedArea: 'מוערכות',
    normalizedArea: 'מוערכות 100%',

    histogramChart: 'היסטוגרמה',
    histogramFrequency: 'תדירות',

    combinationChart: 'שילוב',
    columnLineCombo: 'עמודות וקו',
    AreaColumnCombo: 'אזור ועמודות',

    // Charts
    pivotChartTitle: 'תרשים צירופים',
    rangeChartTitle: 'תרשים טווח',
    settings: 'הגדרות',
    data: 'נתונים',
    format: 'תבנית',
    categories: 'קטגוריות',
    defaultCategory: '(ללא)',
    series: 'סדרות',
    xyValues: 'ערכי XY',
    paired: 'מצב זוגי',
    axis: 'ציר',
    navigator: 'נווט',
    color: 'צבע',
    thickness: 'עובי',
    xType: 'סוג X',
    automatic: 'אוטומטי',
    category: 'קטגוריה',
    number: 'מספר',
    time: 'זמן',
    autoRotate: 'סיבוב אוטומטי',
    xRotation: 'סיבוב X',
    yRotation: 'סיבוב Y',
    ticks: 'סימניות',
    width: 'רוחב',
    height: 'גובה',
    length: 'אורך',
    padding: 'ריפוד',
    spacing: 'ריווח',
    chart: 'תרשים',
    title: 'כותרת',
    titlePlaceholder: 'כותרת התרשים - לחץ פעמיים לעריכה',
    background: 'רקע',
    font: 'גופן',
    top: 'עליון',
    right: 'ימין',
    bottom: 'תחתון',
    left: 'שמאל',
    labels: 'תוויות',
    size: 'גודל',
    minSize: 'גודל מינימלי',
    maxSize: 'גודל מקסימלי',
    legend: 'מקרא',
    position: 'מיקום',
    markerSize: 'גודל מרקר',
    markerStroke: 'מסגרת מרקר',
    markerPadding: 'ריפוד מרקר',
    itemSpacing: 'ריווח פריט',
    itemPaddingX: 'ריפוד פריט X',
    itemPaddingY: 'ריפוד פריט Y',
    layoutHorizontalSpacing: 'ריווח אופקי',
    layoutVerticalSpacing: 'ריווח אנכי',
    strokeWidth: 'רוחב קו',
    lineDash: 'קו מקווקו',
    offset: 'היסט',
    offsets: 'היסטים',
    tooltips: 'תיבות מידע',
    callout: 'תיבת התראה',
    markers: 'מרקרים',
    shadow: 'צל',
    blur: 'טשטוש',
    xOffset: 'היסט X',
    yOffset: 'היסט Y',
    lineWidth: 'עובי קו',
    normal: 'רגיל',
    bold: 'מודגש',
    italic: 'נטוי',
    boldItalic: 'מודגש נטוי',
    predefined: 'מוגדר מראש',
    fillOpacity: 'אטימות מילוי',
    strokeOpacity: 'אטימות קו',
    histogramBinCount: 'ספירת תאים',
    columnGroup: 'עמודה',
    barGroup: 'טור',
    pieGroup: 'עוגה',
    lineGroup: 'קו',
    scatterGroup: 'XY (פיזור)',
    areaGroup: 'אזור',
    histogramGroup: 'היסטוגרמה',
    combinationGroup: 'שילוב',
    groupedColumnTooltip: 'קיבוץ',
    stackedColumnTooltip: 'מוערכות',
    normalizedColumnTooltip: 'מוערכות 100%',
    groupedBarTooltip: 'קיבוץ',
    stackedBarTooltip: 'מוערכות',
    normalizedBarTooltip: 'מוערכות 100%',
    pieTooltip: 'עוגה',
    doughnutTooltip: 'תופסת',
    lineTooltip: 'קו',
    groupedAreaTooltip: 'אזור',
    stackedAreaTooltip: 'מוערכות',
    normalizedAreaTooltip: 'מוערכות 100%',
    scatterTooltip: 'פיזור',
    bubbleTooltip: 'בועה',
    histogramTooltip: 'היסטוגרמה',
    columnLineComboTooltip: 'עמודות וקו',
    areaColumnComboTooltip: 'אזור ועמודות',
    customComboTooltip: 'שילוב מותאם אישית',
    noDataToChart: 'אין נתונים זמינים לתרשים.',
    pivotChartRequiresPivotMode: 'תרשים צירופים דורש מצב צירופים מופעל.',
    chartSettingsToolbarTooltip: 'תפריט',
    chartLinkToolbarTooltip: 'קישור לגריד',
    chartUnlinkToolbarTooltip: 'ביטול קישור מהגריד',
    chartDownloadToolbarTooltip: 'הורדת התרשים',
    seriesChartType: 'סוג תרשים סדרות',
    seriesType: 'סוג סדרות',
    secondaryAxis: 'ציר משני',

    // ARIA
    ariaChecked: 'מסומן',
    ariaColumn: 'עמודה',
    ariaColumnGroup: 'קבוצת עמודות',
    ariaColumnList: 'רשימת עמודות',
    ariaColumnSelectAll: 'בחר את כל העמודות',
    ariaDateFilterInput: 'תיבת קלט סינון תאריכים',
    ariaDefaultListName: 'רשימה',
    ariaFilterColumnsInput: 'תיבת קלט סינון עמודות',
    ariaFilterFromValue: 'ערך מסנן מ',
    ariaFilterInput: 'תיבת קלט סינון',
    ariaFilterList: 'רשימת סינון',
    ariaFilterToValue: 'ערך מסנן אל',
    ariaFilterValue: 'ערך מסנן',
    ariaFilterMenuOpen: 'פתח תפריט סינון',
    ariaFilteringOperator: 'מפעיל סינון',
    ariaHidden: 'מוסתר',
    ariaIndeterminate:'לא מוגדר',
    ariaInputEditor: 'עורך קלט',
    ariaMenuColumn: 'לחץ על CTRL ENTER כדי לפתוח תפריט עמודה.',
    ariaRowDeselect: 'לחץ על SPACE כדי לבטל בחירה בשורה זו',
    ariaRowSelectAll: 'לחץ על SPACE כדי לשנות את בחירת כל השורות',
    ariaRowToggleSelection: 'לחץ על SPACE כדי לשנות את בחירת השורה',
    ariaRowSelect: 'לחץ על SPACE כדי לבחור את השורה',
    ariaSearch: 'חיפוש',
    ariaSortableColumn: 'לחץ על ENTER כדי למיין',
    ariaToggleVisibility: 'לחץ על SPACE כדי לשנות את הראות',
    ariaToggleCellValue: 'לחץ על SPACE כדי לשנות את ערך התא',
    ariaUnchecked: 'לא מסומן',
    ariaVisible: 'מוצג',
    ariaSearchFilterValues: 'חיפוש בערכי הסינון',

    // ARIA Labels for Drop Zones
    ariaRowGroupDropZonePanelLabel: 'קבוצות שורות',
    ariaValuesDropZonePanelLabel: 'ערכים',
    ariaPivotDropZonePanelLabel: 'תגיות עמודות',
    ariaDropZoneColumnComponentDescription: 'לחץ DELETE כדי להסיר',
    ariaDropZoneColumnValueItemDescription: 'לחץ ENTER כדי לשנות את סוג האגרגציה',
    ariaDropZoneColumnGroupItemDescription: 'לחץ ENTER כדי למיין',
    ariaDropZoneColumnComponentAggFuncSeparator: ' של ',
    ariaDropZoneColumnComponentSortAscending: 'מיון עולה',
    ariaDropZoneColumnComponentSortDescending: 'מיון יורד',

    // ARIA Labels for Dialogs
    ariaLabelColumnMenu: 'תפריט עמודות',
    ariaLabelCellEditor: 'עורך תא',
    ariaLabelDialog: 'דיאלוג',
    ariaLabelSelectField: 'בחירת שדה',
    ariaLabelTooltip: 'הסבר קצר',
    ariaLabelContextMenu: 'תפריט הקשר',
    ariaLabelSubMenu: 'תת תפריט',
    ariaLabelAggregationFunction: 'פונקציית אגרגציה',

    // Number Format (Status Bar, Pagination Panel)
    thousandSeparator: ',',
    decimalSeparator: '.',

    // Data types
    true: 'נכון',
    false: 'לא נכון',
    invalidDate: 'תאריך לא תקין',
    invalidNumber: 'מספר לא תקין',
    january: 'ינואר',
    february: 'פברואר',
    march: 'מרץ',
    april: 'אפריל',
    may: 'מאי',
    june: 'יוני',
    july: 'יולי',
    august: 'אוגוסט',
    september: 'ספטמבר',
    october: 'אוקטובר',
    november: 'נובמבר',
    december: 'דצמבר',
};