const AG_GRID_LOCALE_PT = {
    // Seleção do filtro
    selectAll: '(Destacar tudo)',
    selectAllSearchResults: '(Destacar todos os resultados da pesquisa)',
    searchOoo: 'Pesquisar...',
    blanks: '(Espaços em branco)',
    noMatches: 'Nenhuma correspondência',
  
    // Filtro numérico e filtro de texto
    filterOoo: 'Filtragem...',
    equals: 'Igual',
    notEqual: 'Diferente',
    empty: 'Vazio',
  
    // Filtro numérico
    lessThan: 'Menos de',
    greaterThan: 'Mais de',
    lessThanOrEqual: 'Menor ou igual a',
    greaterThanOrEqual: 'Maior ou igual a',
    inRange: 'Entre',
    inRangeStart: 'De',
    inRangeEnd: 'Até',
  
    // Filtro de texto
    contains: 'Contém',
    notContains: 'Não contém',
    startsWith: 'Começa com',
    endsWith: 'Termina em',
  
    // Filtro de data
    dateFormatOoo: 'dd-mm-yyyy',
  
    // Condições de filtragem
    andCondition: 'E',
    orCondition: 'OU',
  
    // Botões de filtro
    applyFilter: 'Aplicar filtro',
    resetFilter: 'Reiniciar filtro',
    clearFilter: 'Limpar filtro',
    cancelFilter: 'Cancelar',
  
    // Cabeçalhos de filtro
    textFilter: 'Filtro de texto',
    numberFilter: 'Filtro numérico',
    dateFilter: 'Filtrar por data',
    setFilter: 'Selecionar filtro',
  
    // Painel lateral
    columns: 'Colunas',
    filters: 'Filtros',
  
    // Barra de ferramentas da coluna
    pivotMode: 'Modo de quadro resumo',
    groups: 'Grupos de linhas',
    rowGroupColumnsEmptyMessage: 'Arrastar e largar aqui para agrupar por linhas',
    values: 'Valores',
    valueColumnsEmptyMessage: 'Arrastar e largar aqui para agregação',
    pivots: 'Títulos de coluna',
    pivotColumnsEmptyMessage: 'Arrastar e largar aqui para definir os títulos das colunas',
  
    // Cabeçalho de grupo de colunas por defeito
    group: 'Grupo',
  
    // Outros
    loadingOoo: 'A carregar...',
    noRowsToShow: 'Sem dados',
    enabled: 'Incluído',
  
    // Menu
    pinColumn: 'Fixar a coluna',
    pinLeft: 'Fixar à esquerda',
    pinRight: 'Fixar à direita',
    noPin: 'Não fixar',
    valueAggregation: 'Agregação por valor',
    autosizeThiscolumn: 'Define automaticamente o tamanho desta coluna',
    autosizeAllColumns: 'Dimensionar automaticamente todas as colunas',
    groupBy: 'Agrupar por',
    ungroupBy: 'Desagrupar por',
    resetColumns: 'Repor colunas',
    expandAll: 'Expandir tudo',
    collapseAll: 'Recolher tudo',
    copy: 'Copiar',
    ctrlC: 'Ctrl+C',
    copyWithHeaders: 'Copiar com cabeçalhos',
    paste: 'Colar',
    ctrlV: 'Ctrl+V',
    export: 'Exportar',
    csvExport: 'Exportar para CSV (.csv)',
    excelExport: 'Exportar para Excel (.xlsx)',
    excelXmlExport: 'Exportar para XML (.xml)',
  
    // Agregação do menu corporativo e da barra de estado
    sum: 'Soma',
    min: 'Mínimo',
    max: 'Máximo',
    none: 'Nenhum',
    count: 'Contar',
    avg: 'Média',
    filteredRows: 'Linhas filtradas',
    selectedRows: 'Linhas selecionadas',
    totalRows: 'Total de linhas',
    totalAndFilteredRows: 'Linhas totais e filtradas',
    more: 'Mais',
    to: 'até',
    of: 'de',
    page: 'Página',
    nextPage: 'Página seguinte',
    lastPage: 'Última página',
    firstPage: 'Primeira página',
    previousPage: 'Página anterior',
    pageSizeSelectorLabel: 'Tamanho da página:',
    // Menu empresarial (gráficos)
    pivotChartAndPivotMode: 'Gráfico de resumo e modo de resumo',
    pivotChart: 'Pivot chart',
    chartRange: 'Chart range',
  
    columnChart: 'Column chart',
    groupedColumn: 'Grouped column',
    stackedColumn: 'Stacked column',
    normalizedColumn: 'Normalized column',
  
    barChart: 'Bar chart',
    groupedBar: 'Grouped bar',
    stackedBar: 'Stacked bar',
    normalizedBar: 'Normalized bar',
  
    pieChart: 'Pie chart',
    pie: 'Pie',
    doughnut: 'Donuts',
  
    line: 'Line',
  
    xyChart: 'XY chart',
    scatter: 'Scatter',
    bubble: 'Bubble',
  
    areaChart: 'Area chart',
    area: 'Area',
    stackedArea: 'Stacked area',
    normalizedArea: 'Normalized area',
  
    histogramChart: 'Histogram chart',
  
    // Gráficos
    pivotChartTitle: 'Título do gráfico',
    rangeChartTitle: 'Título do gráfico',
    settings: 'Definições',
    data: 'Dados',
    format: 'formato',
    categories: 'Categorias',
    defaultCategory: '(Categoria predefinida)',
    series: 'Series',
    xyValues: 'X Y Valores',
    paired: 'Emparelhado',
    axis: 'axis',
    navigator: 'Navegação',
    color: 'Cor',
    thickness: 'Espessura',
    xType: 'X Tipo',
    automatic: 'Automaticamente',
    category: 'Categoria',
    number: 'Número',
    time: 'Tempo',
    xRotation: 'Rotação X',
    yRotation: 'Rotação Y',
    ticks: 'Marcas',
    width: 'Largura',
    height: 'Altura',
    length: 'Comprimento',
    padding: 'Preenchimento',
    spacing: 'Espaçamento',
    chart: 'Gráfico',
    title: 'Título',
    titlePlaceholder: 'Título do gráfico - clique duas vezes para editar',
    background: 'Fundo',
    font: 'Fonte',
    top: 'Topo',
    right: 'Direita',
    bottom: 'Fundo',
    left: 'Esquerda',
    labels: 'Etiquetas',
    size: 'Tamanho',
    minSize: 'Tamanho mínimo',
    maxSize: 'Tamanho máximo',
    legend: 'Legenda',
    position: 'Posição',
    markerSize: 'Tamanho do marcador',
    markerStroke: 'Traço do marcador',
    markerPadding: 'Preenchimento do marcador',
    itemSpacing: 'Distância entre itens',
    itemPaddingX: 'Preenchimento de item X',
    itemPaddingY: 'Preenchimento de item Y',
    layoutHorizontalSpacing: 'Espaçamento horizontal',
    layoutVerticalSpacing: 'Espaçamento vertical',
    strokeWidth: 'Largura do marcador',
    offset: 'Offset',
    offsets: 'Offsets',
    tooltips: 'Dicas',
    callout: 'Desafio',
    markers: 'Marcadores',
    shadow: 'Sombra',
    blur: 'Desfocagem',
    xOffset: 'Offset по X',
    yOffset: 'Offset по Y',
    lineWidth: 'Largura da linha',
    normal: 'Normal',
    bold: 'Negrito',
    italic: 'Itálico',
    boldItalic: 'Negrito itálico',
    predefined: 'Pré-definido',
    fillOpacity: 'Opacidade do preenchimento',
    strokeOpacity: 'Opacidade do marcador',
    histogramBinCount: 'Número de segmentos',
    columnGroup: 'Column group',
    barGroup: 'Bar group',
    pieGroup: 'Pie group',
    lineGroup: 'Line group',
    scatterGroup: 'Scatter group',
    areaGroup: 'Area group',
    histogramGroup: 'Histogram group',
    groupedColumnTooltip: 'Grouped column tooltip',
    stackedColumnTooltip: 'Stacked column tooltip',
    normalizedColumnTooltip: 'Normalized column Tooltip',
    groupedBarTooltip: 'GroupedBar tooltip',
    stackedBarTooltip: 'StackedBar tooltip',
    normalizedBarTooltip: 'NormalizedBar tooltip',
    pieTooltip: 'Pie tooltip',
    doughnutTooltip: 'doughnut tooltip',
    lineTooltip: 'Line tooltip',
    groupedAreaTooltip: 'Grouped area tooltip',
    stackedAreaTooltip: 'Stacked area tooltip',
    normalizedAreaTooltip: 'Normalized area tooltip',
    scatterTooltip: 'Scatter tooltip',
    bubbleTooltip: 'Bubble tooltip',
    histogramTooltip: 'Histogram tooltip',
    noDataToChart: 'Não há dados para apresentar no gráfico.',
    pivotChartRequiresPivotMode: 'Para um gráfico de resumo, é necessário ativar o modo de gráfico de resumo.',
    chartSettingsToolbarTooltip: 'Chart settings toolbar tooltip',
    chartLinkToolbarTooltip: 'Chart link toolbar tooltip',
    chartUnlinkToolbarTooltip: 'Chart unlink toolbar tooltip',
    chartDownloadToolbarTooltip: 'Chart download toolbar tooltip',
  
    // ARIA
    ariaHidden: 'Oculto',
    ariaVisible: 'Visível',
    ariaChecked: 'Verificado',
    ariaUnchecked: 'Não verificado',
    ariaIndeterminate: 'Indeterminado',
    ariaColumnSelectAll: 'Mudar para a seleção de todas as colunas',
    ariaInputEditor: 'Editor de entradas',
    ariaDateFilterInput: 'Introduzir um filtro de data',
    ariaFilterInput: 'Entrada do filtro',
    ariaFilterColumnsInput: 'Introduzir um filtro de coluna',
    ariaFilterValue: 'Valor do filtro',
    ariaFilterFromValue: 'Filtrar a partir do valor',
    ariaFilterToValue: 'Filtrar para um valor',
    ariaFilteringOperator: 'Operador de filtro',
    ariaColumnToggleVisibility: 'Alternar a visibilidade da coluna',
    ariaColumnGroupToggleVisibility: 'Alternar a visibilidade de um grupo de colunas',
    ariaRowSelect: 'Prima a tecla ESPAÇO para realçar esta linha',
    ariaRowDeselect: 'Prima ESPAÇO para anular a seleção desta linha',
    ariaRowToggleSelection: 'Prima ESPAÇO para alternar a seleção de linha',
    ariaRowSelectAll: 'Prima ESPAÇO para alternar a seleção de todas as linhas',
    ariaSearch: 'Pesquisar',
    ariaSearchFilterValues: 'Pesquisa de valores por filtro',
  }
  